### ISSUE TITLE
How to expose Rust functions to the JS runtime?

### ISSUE THREAD

**Issue by juh9870** [Bromeon/js-sandbox#18] opened 2023-03-20 11:29 UTC
To expose functions to JS, I need access to JsRuntime, or an ability to pass extensions to a script during initialization, but as far as I can see, neither is possible currently. Am I missing something?

**Comment by Bromeon** [comment] 2023-03-20 12:33
Accessing Rust from JS is currently not supported, by design. See discussion in #12 🙂

**Comment by Bromeon** [comment] 2023-04-02 09:36
Closing as answered.

**Closed by Bromeon** 2023-04-02 09:36 UTC
Labels: question
